CREATE TABLE [dbo].[tbLog]
(
    [Id] INT NOT NULL  IDENTITY, 
    [Id_tbSistema] INT NULL,
    [Id_tbSeveridade] INT NULL, 
    [Id_tbPrioridade] INT NULL, 
    [Id_tbAmbiente] INT NULL, 
    [Id_tbPlataforma] INT NULL, 
    [Id_tbSituacao] INT NULL, 
    [Codigo] VARCHAR(50) NULL, 
    [Descricao] VARCHAR(MAX) NULL, 
    [Metodo] VARCHAR(100) NULL, 
    [Classe] VARCHAR(100) NULL, 
    [Package] VARCHAR(100) NULL, 
    [TipoExcecao] VARCHAR(150) NULL,
    [Arquivo] VARCHAR(250) NULL, 
    [Localizacao] VARCHAR(250) NULL,
    [DataHora] DATETIME NOT NULL DEFAULT GetDate(), 
    [Deletado] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT [PK_tbLog] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_tbLog_tbSistema] FOREIGN KEY ([Id_tbSistema]) REFERENCES [tbSistema]([Id]),
    CONSTRAINT [FK_tbLog_tbSeveridade] FOREIGN KEY ([Id_tbSeveridade]) REFERENCES [tbSeveridade]([Id]),
    CONSTRAINT [FK_tbLog_tbPrioridade] FOREIGN KEY ([Id_tbPrioridade]) REFERENCES [tbPrioridade]([Id]),
    CONSTRAINT [FK_tbLog_tbAmbiente] FOREIGN KEY ([Id_tbAmbiente]) REFERENCES [tbAmbiente]([Id]),
    CONSTRAINT [FK_tbLog_tbPlataforma] FOREIGN KEY ([Id_tbPlataforma]) REFERENCES [tbPlataforma]([Id]),
    CONSTRAINT [FK_tbLog_tbSituacao] FOREIGN KEY ([Id_tbSituacao]) REFERENCES [tbSituacao]([Id])    
)
